#!/usr/bin/env ruby

require 'yaml'

sha = `git rev-parse HEAD`
secrets = YAML.load(File.read(File.expand_path("../../../../config/secrets.yml", __FILE__)))
github_token = secrets['development']['github_credentials']['access_token']

system("curl", "-i", "-H", "Content-Type: application/json", "-u", "#{github_token}:x-oauth-basic", "-X", "POST", "https://api.github.com/repos/dylanahsmith/junk/statuses/#{sha}", "-d", '{ "state": "success" }')
